### ISSUE TITLE
Exif data error

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1028]
<img width="352" alt="Screenshot 2024-01-12 at 12 19 50 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/12838725-a433-4f92-b1bd-c0a060f3e438">

I get warnings about this promise rejection in pretty random places, like while I'm on the Explore screen or sometimes when I first start the app. We should make sure we're only parsing EXIF data when we need to.

**Comment by budowski** [comment]
@albullington - I did a tiny fix (info instead of warning when encountering an EXIF error), in a new PR - however, I double checked all the code, this flow could only happen when either: Sharing a photo into iNat or importing a photo.
Could it be that these are older warnings (not "fresh") that were left in the call stack while you were previously using the app?

**Comment by albullington** [comment]
@budowski I guess that's possible! It's a warning I was seeing pretty regularly, but I didn't pay much attention to whether I was doing a fresh install of the app or not before seeing it.

**Comment by kueda** [comment]
So you have no repro conditions here, @albullington? Not even related to importing photos that might not have coordinates?

**Comment by albullington** [comment]
No, it doesn't pop up for me specifically around imports -- I'd say I've seen it the most when tapping Explore on the TabBar, when I'm not importing anything at all. It's also possible it's happening for me in the simulator more than on a real device -- I can keep an eye out for this.

**Comment by albullington** [comment]
Closing this for now since I'm not seeing it in the latest build.
