### ISSUE TITLE
UI issues in MyObservations list while uploading

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1426]
There are a few UI issues on MyObservations while uploading.

1. Scrolling is jittery while the uploads are happening
2. The top two observations in MyObservations list disappear from view after scrolling down and scrolling back up again

Repro steps:
1. Make a handful of observations in the AI Camera
2. Tap upload X observations in the MyObservations toolbar
3. Scroll down, then scroll back up. Scroll is jittery and observations are missing

Here are some video recordings of the issues in Slack: https://inaturalist.slack.com/archives/C02G5AATVGA/p1713756149536669

**Comment by kueda** [comment]
FWIW, I was able to replicate the jitter and #1599 will address that, but I couldn't replicate the disappearing observations. That *might* be observation list items getting a bit stuck in their transitioning animation between uploading and complete states, and/or maybe it has to do with [FlashList recycling](https://shopify.github.io/flash-list/docs/recycling), but I'm not sure what remedies to try since I can't replicate.

**Comment by kueda** [comment]
Apparently Carrie can't replicate the disappearing obs any more either, so I'm going to close.
