### ISSUE TITLE
ObsEdit doesn't show photos for when accessed via ObsDetails

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1486]
**Describe the bug**
ObsEdit is not displaying photos in EvidenceList and shows "no evidence" warning for observations created within the app.

Additionally, the ObsEdit screen may show a stale identification instead of the identification of the tapped obs.

**To Reproduce**
1. Tap on an observation created in iNaturalist Next on MyObs
2. Tap on pencil icon via ObsDetails
3. Evidence section will show no photos, even though observation has photos

**Screenshots**
For staff, screen recording [here](https://inaturalist.slack.com/archives/C02G5AATVGA/p1714570696663539?thread_ts=1714570520.468619&cid=C02G5AATVGA)

- [ ] Photos should display in ObsEdit EvidenceList
- [ ] Text should read "Edit Observation" instead of "New Observation" when navigating to a locally saved observation
- [ ] ObsEdit should show identification for the saved observation, not the previous ObsEdit screen's identification

**Comment by kueda** [comment]
FWIW, I think this happens for any observation accessed via ObsDetails, no matter where it was created. Photos do appear on ObsEdit before they are uploaded. I added a [partial fix](https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/components/ObsEdit/EvidenceSection.js#L63-L68), but the real culprit is just that we're not passing around a single type of observation, and are instead treating API responses, local Observation model records, and JSONified versions of both as as if they were all the same type, and they're not.
