### ISSUE TITLE
Suggestions wrong when choosing a photo

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1563]
**Describe the bug**
Sometimes Suggestions shows insane results when choosing the photo to show suggestions for.

**To Reproduce**
1. Go to https://www.inaturalist.org/observations/216975011 in the app
2. Tap on SUGGEST ID
3. When you land on Suggestions no photo is selected, which seems like a bug, but the actual suggestions look ok:
    ![IMG_0842](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/51371f13-ce3c-4c5a-b746-3bad38d1c7ee)
5. Tap on the first photo totally different suggestions:
    ![IMG_0843](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/95f5964d-2df5-444a-96a2-5d363725ea7d)
6. Tap on the second photo and you get increasingly weird suggestions:
    ![IMG_0844](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/0583ec98-8099-496e-90d1-2f24ce72ead0)
7. Tap on the last photo and you get suggestions in the wrong kingdom:
    ![IMG_0845](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/aa0cc368-d59b-4291-886b-8c591855b030)

**Expected behavior**
1. The first photo should be selected when you load Suggestions and that should be what gets sent to `score_image`
2. Tapping on other photos should show suggestions for those photos (the suggestions in my screenshots are too bizarre for me to believe this is really happening)

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.4.1
 - App version: 0.32.3 (91)

**Additional context**
While I see all these requests in the app's network logger, I don't see them all in Kibana, so maybe this is a weird caching issue? Seems like there might be something odd going on with handling response data as well.

**Comment by albullington** [comment]
I tried to replicate by opening this observation in the app, and I'm seeing a majority of allium suggestions when tapping all three photos. I made a change in a recent [suggestions PR](https://github.com/inaturalist/iNaturalistReactNative/pull/1649/files#diff-9cbc32e45f7266c98ed4a99d869c2c61607eb2f9e59211f6956b3400520870d3) that ensures we're resizing and submitting the medium-sized photo for any photo selected, rather than only the first photo selected, and I suspect that fixed this issue. Before, we would have been resizing and submitting the small square photos for the second and third photo, which wouldn't have resulted in very accurate suggestions.

I can see inaccurate suggestions when checking the latest TestFlight build (0.32.6), so it was definitely fixed since then.

Closed by #1649 (I believe).
