### ISSUE TITLE
Tapping sync button in toolbar syncs forever

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1630]
**Describe the bug**
Tapping the sync button in the toolbar when you have no observations to upload syncs forever

**To Reproduce**
1. Sign in to an account with observations
2. Tap the sync button in the toobar
3. Toolbar icon starts to rotate and status says "Syncing..."... and stays that way until you force quit the app or sign out

**Expected behavior**
Syncing status should stop when syncing stops, and syncing should not last forever/

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: 17.4.1
 - App version: 0.32.6 (94)

**Additional context**
Abhas and I are both experiencing this under very good network conditions, so this isn't because the request is timing out. That case *might* be worth addressing but this is something else.

**Comment by abhasinat** [comment]
When a user taps the sync button:
- & the user has observations to upload:
     - UI should show "uploading X observations"
     - First, sync all deletions
     - then upload all pending observations
     - then, fetch all remote observations
     - UI changes to our existing "X observations uploaded" with a checkmark and any relevant error states
- & the user does not have any observations to upload
     - UI should show "Syncing..."
     - First, sync all deletions
     - then, fetch all remote observations
     - sync wheel stops spinning & UI returns to default state with no text

**Comment by albullington** [comment]
@abhasinat a couple questions on this:

- Does the toolbar display the "Syncing..." message when a user lands on the MyObservations screen and the syncing starts automatically? Or since this happens in the background, does the user only see "X observations to upload" or no text?
- When does a user see the "X observations deleted" or "Deleting x observations" text? My current understanding is that this text only shows when a user navigates to ObsEdit, taps delete in the kebab menu, and then returns to MyObservations. So they would only ever see "1 observation deleted." Is this what you're thinking or am I missing something here?

**Comment by abhasinat** [comment]
great questions.

- A user should NOT see "Syncing..." when a user lands on MyObs and the syncing starts automatically. They should see either no text if they have no obs to upload or "X obs to upload" if they have saved observations
- Exactly right. The only time a user needs confirmation that an obs is deleted is when they manually delete the obs from obs edit and returns to myobs, so they will only ever see "1 observation deleted." maybe there'll be some batch delete/edit functionality in the future that'll show other text, but that's the only message a user will see about deletions for now.
