### ISSUE TITLE
Camera without flash throws error

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1638]
**Describe the bug**

We're throwing a camera error when the user's device doesn't have flash available. It's unclear where exactly this is happening, but we might be showing the flash button for devices where flash is unavailable, or we might be using the flash setting in `initialPhotoOptions` when a user takes a photo but doesn't have a device with flash. So far, this isn't impacting a ton of users, but we should investigate and make sure we're only taking photos with flash if a user has flash on their device.

`The Camera Device does not have a flash unit! Make sure you select a device where `device.hasFlash`/`device.hasTorch` is true.`

**Context (please complete the following information):**
 - App version: 0.32.6

**Comment by jtklein** [comment]
I am closing this off without changes after a code audit I did just now. We should be guarded against this error under normal circumstances because we 1) do not show the flash toggle button when `device.hasFlash` is false and 2) start off with initial take photo options without flash setting if device.hasFlash is false.
I can also only see one error logged with this error message and it came from a server rack mounted google test device which might have a special hardware setup: https://www.inaturalist.org/observations/196244827
