### ISSUE TITLE
React Query getting stuck offline

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1847]
Tony and others have [reported](https://inaturalist.slack.com/archives/C02G5AATVGA/p1721321111647369) a problem where the uploads fail and will not succeed until the app is restarted. There is no crash, just the "1 upload failed" error in the toolbar. Looking at Tony's log, the only errors I'm seeing are `Network request failed` and various retries, but his screenshot shows that he had a good connection, and he reports that simply force-quitting the app and trying again "fixes" the problem.

That suggests to me that some part of the app thinks it's offline when it's not. My suspicion is that it's React Query since that seems to be where these are coming from, so I would start investigating there.

Unfortunately we don't have solid repro steps yet.

**Comment by albullington** [comment]
Going to close this since we addressed the React Query part of this, and we don't have repro steps for the upload failures (which don't use React Query). It's possible there were too many React Query retries happening all at once, because the app acted like it was offline, and that would take away bandwidth for the uploads to happen. Feel free to reopen if we continue bumping into this upload issue.
