### ISSUE TITLE
Add Gallery button inside AI Camera

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1848]
We decided that we want a link to the gallery inside the AI Camera for soft launch.

Here are the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=3110-19359&t=4T8KNWs0DYZBEwWr-11) for the update AI camera.
- [x] Add a new button to the AI Camera in the bottom right - it's a rounded square with a white outline, 50% Dark Gray fill, and the gallery icon on it. Make sure it's vertically centered with the capture and close buttons, and right-aligned with the zoom, flash, and flip camera buttons.
- [x] Clicking this button should do the exact same thing as if i clicked the gallery button in the obs wheel: it should open the photo picker
     - if a user has not given gallery permissions, show the gallery permissions gate
     - if the user has denied gallery permissions, show the gallery permissions denied screen
     - if a user selects 1 photo, open suggestions
     - if they choose multiple photos, open the group photos screen
- [x] move the zoom, flash, and flip camera buttons up to make room for this button.
- [x] When the device is rotated, make sure that the gallery icon inside the square, just like all the other buttons, rotates to match the device's orientation.
- [x] on [iPad](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=3652-21524&t=4T8KNWs0DYZBEwWr-11), this button can be added to the bottom right of the AI camera.

**Comment by albullington** [comment]
@abhasinat do you foresee any odd navigation cases here? I'm thinking about potentially complicated flows like where a user goes from AICamera -> Gallery -> Suggestions -> ObsEdit -> Suggestions -> Gallery. In this case, would they add evidence to their existing observation in ObsEdit from the Gallery, or does their observation get scratched and replaced when they try to navigate forward from the gallery again?

At this point if they tap the back button on the Gallery, does it take them back to the AICamera? (I'm assuming they can back out all the way to MyObs through the Gallery -> AICamera)

If they do back out all the way to AICamera -> Gallery -> Suggestions -> ObsEdit -> Suggestions -> Gallery -> AICamera, I'm assuming this should create a new observation since AICamera can only ever create one observation at a time? What if they already added photos to their observation from the Gallery on the first time through this navigation stack? Do those gallery photos get removed from the observation when they back out to the AICamera?

Are there any gotchas if they navigate back into the Camera/Gallery when adding evidence?
