### ISSUE TITLE
Redo Signup/Login to be through an in-app web browser

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1887]
Change the current signup/login to be through an in-app browser

Might require some design.

**Comment by kueda** [comment]
FWIW, this also requires coordination with the web team to figure out how this would work, so that part is ready for a dev to work on. Ultimately, no matter how the user signs in or signs up, the webview needs to provide the app with a working OAuth access token. Devs in this project need to figure out the best way to receive that (in the URL? as an HTTP header in a response? as JS in the webview sending an explicit message out of the webview?), and the web team needs to figure out what's feasible and secure.

Personally I would start by figuring this out for basic sign in to an existing account, and once that's working, move on to sign up, reset password, and 3rd party.

**Comment by kueda** [comment]
For the record, I think abandoning this in favor of doubling down on our in-app implementation is a bad idea. Sign up, log in, and reset password, along with all their attendant requirements and error states, are exactly the same across the platform. They're also really important and come with legal requirements. Maintaining separate implementations has led to drift in the past, where mobile clients lagged behind the web, and that will just continue with this approach, making it impossible to make rapid changes to these processes that we might need to combat malicious behavior or comply with different legal conditions.

**Comment by kvangork** [comment]
Acknowledged. While functional requirements are mostly common, interface constraints and opportunities are not. The in-app implementation gives us a higher ceiling for user experience quality.
