### ISSUE TITLE
AI Camera button and text on logged out home screen is too low

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1929]
**Describe the bug**
Right now, the logged out home screen looks like this. The button and the "Identify an organism with the iNaturalist AI Camera text" as a group are too low on the screen. I would move it higher so it looks like the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=2920-34430&t=Fpd9fOjOVmOwoZy7-11).
![IMG_0072](https://github.com/user-attachments/assets/c6ad00b1-2f54-4663-8e2c-73e8715d75ea)

**To Reproduce**
1. Open a fresh install of iNat next
2. View the home screen

**Expected behavior**
Placement should be more like this: 
<img width="316" alt="image" src="https://github.com/user-attachments/assets/34178293-84df-405b-a82c-1cdbe22eddf6">

**Context (please complete the following information):**
@iPhone 13 Pro, iOS 17.5.1, 0.39.0+105

**Comment by jtklein** [comment]
I worked on this placement not long ago making it also work on iPad, and am probably the one who introduced this difference to the designs. It seemed to me to be the best compromise because we can’t use flex for this container (ie the empty flash list component). Anyway, if you are working on this make sure your changes also work on iPad.
