### ISSUE TITLE
Explore: My observations + Hide my observations + (new feature) Unobserved by me

### ISSUE THREAD

**Issue by dgilperez** [inaturalist/iNaturalistReactNative#2041]
Two different but related things:

1. Old Android App has these 2 checkbox filters in the Explore page: "show only my observations" and "hide my observations". I think they are very useful filters, and they would be an interesting addition to this app. 
2. Coming from https://github.com/inaturalist/iNaturalistAndroid/issues/1356, I requested to add an additional filter to that list "show unobserved by me". The feature [was requested before at the forum](https://forum.inaturalist.org/t/add-unobserved-by-user-id-to-filters-in-the-apps/10231), even though it generated little debate.

I understand this may not be too high on the priority list or at all, but since 1. is already a feature in the old App, and I see both as related, I thought it was worth it to ask and offer. 

I wonder if you'd be interested in a PR - I could give it a try. I also see this as a nice little thing for a newcomer to the code to flex muscles. I'd be happy to split this into 2 different things. 

If positive, then I'd love to learn how to set the local environment regarding local keys - I started a branch but I reckon I'd need some credentials to some staging? 

Thanks :)

**Comment by kueda** [comment]
Thanks for the suggestion, @dgilperez. As I mentioned in that other issue, we use https://forum.inaturalist.org/c/feature-requests/16 to solicit and discuss feature requests, and I see you've [chimed in](https://forum.inaturalist.org/t/add-unobserved-by-user-id-to-filters-in-the-apps/10231/9) on the relevant thread, so thank you for that. We use github issues to manage our workload and generally only make them for work that we've decided we want to do on the app, so I'm going to close this for now because we haven't made that decision. We may still decide to add this feature. I think it would be cool, personally.

Regarding development setup, you don't *need* additional credentials to get the app to run, but you will need an iNat oauth app to sign in and a GMaps API key to get Google Maps to display on Android. Without those you can work on things that don't require sign-in or Google Maps. We don't have a staging environment that's open to people who aren't on staff, but I agree that would be really useful if we want to have more open source contributions.

**Comment by dgilperez** [comment]
Got it, thanks for both explanations. I will wait for that decision then. 

About those the first part of the comment, I am not sure if that's on the roadmap or also not, since it was an old feature. I am asking because I have some code in a branch I could share. But as you confirm, it's a signed-in only feature, so probably not the best way to contribute atm.

Good luck with the launch and milestones I see, really looking forward to test this. Just let me know if I can contribute with some of this in the future.
