### ISSUE TITLE
Fastlane doesn't promote draft releases in the Play Store

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#205]
In the current release process you still have to publish the build manually in the Play Store to get it on devices. Fastlane should just do that for you.

**Comment by albullington** [comment]
It looks like the only way to [solve this](https://github.com/fastlane/fastlane/discussions/18293#discussioncomment-4202163) is to promote one of the internal releases to an Alpha track, which requires a dummy app description, icons, screenshots, compliance, etc. We can close the Alpha track immediately since otherwise, the app will be submitted for review (and obviously rejected).

After that, we can remove `release_status: "draft"` from Fastfile and this should let us publish to the internal track with a full rollout.

Any downsides to publishing a temporary Alpha track now? If not, I can go ahead and do this (maybe using the screenshots from Seek).

**Comment by kueda** [comment]
I don't have a problem with pushing a temporary alpha track build. I guess another approach would be to start pushing internal builds for the actual iNaturalist app, right?
