### ISSUE TITLE
My Observations Grid View changes

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2088]
Right now, it's hard to see the images on My Observations Grid view.

Here are some changes to make on Home/My Observations Grid View ONLY (this should NOT apply to explore/observations/grid view)
- [x] Hide the #IDs, #Comments, and quality grade icons
- [x] Instead of two names, show only the first name, and truncate the name to 2 lines with ellipses
     - [x] if my setting is Common Name (Scientific Name), I should see Common Name only
     - [x] if my setting is Scientific Name (Common Name) or Scientific Name, I should see Scientific Name only
     - [x] if my setting is Common Name (Scientific Name) and there is no common name for the organism, I should see Scientific Name only

<img width="397" alt="image" src="https://github.com/user-attachments/assets/bd15741d-8160-48b0-adf0-4e54a694ea08">

**Comment by albullington** [comment]
@abhasinat for this item `Hide the #IDs, #Comments, and quality grade icons`, how do you want to handle the upload icon? I'm assuming you would still like the upload icon to show if an upload is available in GridView, followed by the upload progress and upload complete icon, and instead of fading into ID/Comments/QualityGrade icons it should fade into nothing when an upload completes. Does that sound right?

**Comment by abhasinat** [comment]
exactly!
