### ISSUE TITLE
Observation not shown when linked pressed in another app while explore filters open

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#2316]
**Describe the bug**
If Explore filters are open and the app is in the background and an iNat link in another app is pressed, the app doesn't show the observation.

**To Reproduce**
1. Open Explore Filters
2. Go to another app and tap on an iNat observation link
3. See error

**Expected behavior**
The app should show the observation if a link is pressed.

**Context (please complete the following information):**
 - Device: iPhone
 - OS: 18.01
 - App version: 0.51.0

**Additional context**
Carrie experienced this bug

**Comment by kvangork** [comment]
@angielt I think I've seen a more general version of this bug, but it might have the same solution. I had ObsDetail open, then went back to my email, tapped another observation, and iNat Next came back up but stayed on the previous observation instead of transitioning to the one I had tapped.
This might be a bad idea, so feel free to disregard it: if I were starting on this bug personally I'd look at ways to reset navigation to one of the root tabs before pushing the link destination onto the stack.
