### ISSUE TITLE
Import photos using native photo chooser

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#431]
Instead of using `react-native-camera-roll`, we'd like to switch to using the native photo selection system on iOS and Android. An example of an app that works like this is Gmail -- when you go to attach a photo to an email, the native photo selector pops up on top of the app. The user can choose a photo and then will be returned to the app with their selected photo.

At first glance it looks like [react-native-image-picker](https://github.com/react-native-image-picker/react-native-image-picker) is a library that would work for this.

Todos:

- [x] Get native photo picker working on Android
- [x] Get native photo picker working on iOS
- [x] Ensure native photo picker is used for importing new photos to Group Photos *and* selecting photos for an existing observation (i.e. on Obs Edit)
- [x] Ensure native photo picker allows selection of multiple photos
- [ ] Check for compatibility issues on older devices. (For example, I believe iOS introduced a new[ Photos Picker](https://developer.apple.com/documentation/photokit/selecting_photos_and_videos_in_ios) that only works on iOS 15+, so we may need a different solution for phones with an older OS)
- [x] Make sure we can still get coordinates from exif data

**Comment by Chrischuck** [comment]
@albullington I tried out `react-native-image-picker` but exif data doesn't work for ios. `expo-image-picker` might work?

**Comment by Chrischuck** [comment]
I played around w/ this for a few hours and got to a point where I found something that should work moving forward. There's a ton of moving pieces in the `ObsEditProvider`, which I still haven't figured out.

But I threw up a draft PR #509 which I got working to some extent.

`react-native-image-picker` wasn't playing nice with `@bam.tech/react-native-image-resizer` and I couldn't figure out why for the life of me. I tried `expo-image-picker` and couldn't even get that working to begin with. 

Lastly tried out [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) which seems to work with `@bam.tech/react-native-image-resizer` just fine and can pull `exif` data from the get-go which is nice. I also think it can resize images from the start so `@bam.tech/react-native-image-resizer` might not even be needed.

I think for me, a lot of the code can be removed since we're now using a native image picker - but on my end I'm lost in the flow of the current image picker and how to translate it over.

https://user-images.githubusercontent.com/13311268/221426866-fab46138-e1b0-4d74-a6a8-72cbd2830cdd.mov

**Comment by Chrischuck** [comment]
@albullington Did a ton of digging, came across [this](https://github.com/baronha/react-native-multiple-image-picker#readme) library. Although the components are natively built, it doesn't use the actual native pickers respectively.

I believe it should return the path to the original file and not create a copy
