### ISSUE TITLE
Update colors and unify usage in the app

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#455]
This is what I would include in this task:
- [ ] Update the color scheme in the tailwind configuration to only include the currently used colors according to the new design specs.
- [ ] Exchange all usage of colors that are not mentioned in the design specs with the appropriate color according to the designs.
- [ ] Check through the components to set color by using mainly nativewind/tailwind `className` prop where possible. Use a `color` prop for setting the component color only where absolutely necessary.
- [ ] If color value at runtime are needed, exchange usage of `import colors from "styles/tailwindColors"` with `import { useTheme } from "react-native-paper"`.

**Comment by Chrischuck** [comment]
If I could make a suggestion here.

For me the color names aren't intuitive to what you'd think in use. i.e., primary is `darkGray` rather than `iNatGreen`, `onSecondary` is white rather than having `colors.white` be white. Not sure if this is needed because of how the colors trickle down through `react-native-paper`, but again the naming isn't quite as expected.

**Comment by jtklein** [comment]
We want to rely mainly on nativewind/tailwind for styling, so I think it might be worth spreading the colors set in the tailwind config into the react-native-paper theme and then use them with the useTheme hook. So, e.g. then you could use theme.colors.darkGray.
But we also want to set those colors for the primary key and so forth because that overrides the default styling of paper elements (https://callstack.github.io/react-native-paper/theming.html).
