### ISSUE TITLE
Create box shadow on Android for custom header w/ ScrollView

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#517]
In PR [#508](https://github.com/inaturalist/iNaturalistReactNative/pull/508), we decided to punt on getting a working box shadow on Android. The shadow is currently working on iOS, but not Android.

We tried `react-native-fast-shadow` as a solution, but no luck. So this needs more exploration.

I suspect we might need a somewhat hacky solution like what we did for the footer in Seek -- using an image of a shadow, instead of trying to create a shadow with CSS.

**Comment by Chrischuck** [comment]
Tested out `react-native-shadow-2` which I was pretty confident would work - but unfortunately it does not. So this might be a pretty rough bug

**Comment by Chrischuck** [comment]
Figured out that it's because the context header is getting rendered before the screen, so the screen covers up the shadow. Similar to this [issue](https://stackoverflow.com/questions/49078735/react-native-zindex-not-taken-seriously-on-android) in an unrelated repo.

Unfortunately, we can't really re-arrange the dom tree since react-navigation takes care of it.

`elevation` and `zIndex` are being completely ignored here for some aggravating reason

Worst case scenario would be to just include the context header in the screen itself and have react-navigation render no header. That should work.

**Comment by albullington** [comment]
Closed in #528
