### ISSUE TITLE
issues for non-maintainers to take a look at?

### ISSUE THREAD

**Issue by flbn** [inaturalist/iNaturalistReactNative#582]
any issues for casual OSS enthusiasts to take a look at, perhaps something in the backlog?

taking a look at some of these, it's not immediately clear what's a `good first issue`, etc? maybe a top-level issue to track these? idk, just spitballing as i would love to help out with anything i can.

**Comment by jtklein** [comment]
Hello @flbn,
thanks for your feedback. I did make a few "good first issue"s now.

**Comment by kueda** [comment]
I'm going to close this as @jtklein added this label to a few issues. In my experience, it's hard to judge what is a good first issue since we don't know what capabilities people have when they decide to contribute. IMO if you'd like to contribute, have a look at a few issues and try one that seems reasonable to you.
