### ISSUE TITLE
My observations don't automatically download after sign in

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#62]
**Describe the bug**
My observations do not download after sign in.

**To Reproduce**
1. Tap on "menu" in the tab bar and tap on "login" to log in
1. Enter correct credentials to log in
1. Tap on "obs list" in the tab bar to view your observations
1. You still see the default welcome help text even though you're signed in.

**Expected behavior**
I would expect my observations to download after I log in. Actually, I expected to land on My Observations immediately after I logged in and to see that my observations were downloading.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: 0.0.1

**Comment by albullington** [comment]
If a user has say, 10,000 observations, is the goal to download all of them to the mobile device immediately? This is something @abhasinat and I have chatted about a few times, but I don't think we ever got clear on how this is supposed to work. Or do we only need to download the first ~100 observations or so that a user can see immediately in My Observations?

**Comment by kueda** [comment]
In Android we take an infinite scroll approach, and I believe we cache every observation that gets loaded in the local database (@budowski correct me if I'm wrong). @alexshepard can comment on the iOS situation. I should point out that this is never trivial b/c on My Observations you're mixing local-only content with remote content. Things are easier in Explore where it's all remote.
