### ISSUE TITLE
Use nested navigators

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#737]
Currently, the root navigator of the app is a [Drawer Navigator](https://reactnavigation.org/docs/drawer-navigator) (corresponding to the drawer that slides out from the left side of the screen), which contains a single screen, the [Bottom Tabs Navigator](https://reactnavigation.org/docs/bottom-tab-navigator), which contains *every* screen in the app. We did this to address a back button problem in #541, but it has the effect of making all screen transitions instantaneous, and I think it confuses the IA and discourages modularity (e.g. ObsEdit *should* be modular enough to exist in multiple stack navigators without any problems).

So my request here is research at first, maybe leading to a full-scale change:

1. Read up on [nesting navigators](https://reactnavigation.org/docs/nesting-navigators)
1. Experiment with using nested [Native Stack Navigators](https://reactnavigation.org/docs/native-stack-navigator) on a single flow, e.g. MyObs -> ObsDetail -> ObsEdit
1. Report back on whether this seems better and worth doing everywhere

**Comment by albullington** [comment]
Tried experimenting with MyObs -> ObsDetail -> ObsEdit. This gets immediately pretty complicated because there are some screens in this stack that require the Tab navigator to be shown at the bottom of the screen and some that don't.

I tried Drawer -> Tab -> MyObservationsStack (plus all the other screens).

1. MyObs - needs to be nested inside the Tab navigator to display the bottom tabs, which in turn needs to be nested inside the Drawer navigator for the drawer to be able to open and close
2. ObsDetail - needs to be nested inside the Tab navigator
3. ObsEdit - needs a way to *not* display the Tab navigator. According to [react navigation docs](https://reactnavigation.org/docs/hiding-tabbar-in-screens/), the way to accomplish this is by keeping this screen nested outside the Tab navigator. This would mean rewriting the navigators in the Drawer -> Stack -> Tab navigator format, but I think that means we would be splitting ObsEdit and MyObs into different navigators and losing the seamless screen transition that's desired
- worth noting here that we can't use the [custom code](https://github.com/inaturalist/iNaturalistReactNative/blob/0d203dfce012f7f661f4ad2a703c3a2ab6e81ee0/src/navigation/BottomTabNavigator/CustomTabBar.js#L81) we have to hide the tab bar on certain screens in a Drawer -> Tab -> MyObservationsStack setup, because the Tab Bar doesn't maintain a history of what screen in the stack a user is on. If we tried to track this ourselves, it would get complicated because we'd need to track which screen a user is going back to.

I think my recommendations for moving forward would be to experiment with:

1. Dropping the tab navigator altogether [like we did to get around this issue in Seek](https://github.com/inaturalist/SeekReactNative/tree/main/components/Navigation), and instead display a custom footer on the screens that need the tab navigator.
2. Keeping the current nav structure but adding custom transitions for every screen (I think this is likely to get complicated quickly)

Or maybe we could see if there's a different UX that doesn't require the Drawer navigator to be the parent of all screens and the Tab navigator to be nested within it, since this sort of limits our options.
