### ISSUE TITLE
Sign out should delete local records

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#87]
- [x] Add a confirmation modal on the sign out button that says, "Are you sure you want to sign out? This will delete all your observations on this device. It will not affect any observations you've uploaded to iNaturalist."
- [x] If the user chooses to sign out, [delete the Realm database](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#.deleteFile)

**Comment by albullington** [comment]
Any preference on how ObsList should handle this? As is, when a user signs out & the realm file gets deleted, a user who taps on My Observations would still show observations because it's popping the previous My Observations screen to the top of the stack via react-navigation.

A few potential ways we could handle:
- Force My Observations to refresh anytime a user lands on that screen (maybe using `navigation.push` instead of `navigation.navigate`)
- Let My Observations know about the logged in / logged out state of the app & refetch data if a user logs out. This could happen in the actual navigator, maybe by [conditionally rendering](https://reactnavigation.org/docs/auth-flow#define-our-screens) a different My Observations screen if the user is logged out or [passing different params](https://reactnavigation.org/docs/params) to the My Obs screen if a user is logged in/out
