### ISSUE TITLE
Splash screen; restyle

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#898]
Restyle the Splash screen according to the current [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1603-15213&mode=dev).

**Comment by abhasinat** [comment]
SImplified this design in Figma. fwiw- I think we did this in Seek and I really like it. I'd be open to an animation on the splash screen in the future as well

**Comment by kueda** [comment]
The current Figma designs show the "blue wing background" splash screen, even though that matches the "blue wing background" app icon that I think we *don't* want, so I need input form Abhas again on what we actually want here.

**Comment by kueda** [comment]
Ok, this is not working for me. I've tried

1. Adding a UIImage to the LaunchScreen storyboard: it never appears on device
2. Making sure that image is under 100kb: it never appears on device
3. `react-native-bootsplash`: it doesn't support image backgrounds because it doesn't seem doable on Android
4.  Editing Seek to replace its splash image with this one (works) and then making our storyboard match the Seek one exactly, including constraints: the image never appears on device even though it appears just fine when building Seek

So, I have no idea what's going on here. I suspect some weird XCode evil is happening and I just don't know what secret checkbox isn't being checked. Either someone with more experience needs to walk me through this, or someone else needs to give this a try, or we give up on this and keep the (IMO) more sensible white logo on a green background.

**Comment by kueda** [comment]
And now it's working, w/ help from Alex and Amanda. Some important things I've learned about iOS splash/launch screens:

1. You can't have transparency. If you have a `UIImage` with an alpha of something less than 1, iOS won't show it
2. There is a magical launch screen cache somewhere that cannot be cleared without *restarting the device*. Yes, seriously. This was the only way I could get changes to an *image* in my launch screen storyboard to appear on device. Changes to something like view background color worked fine w/o restart. Thanks to Alex for this tip.
3. Positioning and scaling in a storyboard for multiple screen sizes is magical and hard to control. I ended up scaling every element to the size of the screen and controlling the scale of the logo in the logo SVG itself.
